name: 'Terraform Format Check'

on:
  push:
    branches: [ Assignment3 ]

  workflow_dispatch:

jobs:
  terraformFormatCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: |
          terraform fmt -check
          echo $
        continue-on-error: false

      - name: Terraform init & Validate
        run: |
          terraform init
          terraform validate -json
        continue-on-error: false

      - name: Confirm End
        run: echo "End"


